import Head from "next/head";
import { useEffect, useState } from "react";
import useLocalstorage from "../hooks/useLocalStorage";
import IPlaylist from "../interfaces/IPlaylist";
import styles from "../styles/Home.module.css";
import { Youtube } from "../util/Youtube";

export default function Home() {
  const [localPlaylistIDs, setLocalPlaylistIDs] = useLocalstorage<string[]>(
    "playlists",
    []
  );

  const [playlists, setPlaylists] = useState<IPlaylist[]>([]);
  async function addPlaylist(idOrUrl: string) {
    const id = Youtube.playlistIdFromUrl(idOrUrl);
    const response = await fetch(`api/playlist/${id}`);
    if (!response.ok) return;
    const newPlaylist: IPlaylist = await response.json();

    // Don't allow duplicates
    if (playlists.some((e) => e.id === newPlaylist.id)) return;
    const newState = [...playlists, newPlaylist];
    setPlaylists([...newState]);
    setLocalPlaylistIDs([...newState].map((e) => e.id));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>aaa</main>
    </>
  );
}
